### ISSUE TITLE
Block editor not working

### ISSUE THREAD

**Issue by francoisbeyers** [jeffreyvr/thegithubblog#1]
Hi Jeffrey,

I first off want to thank you for creating this! I have been looking for a TailWindCSS/WordPress solution. 
So I am very excited to test this out, and hopefully only use this for my future builds. 

On the offset, I have just cloned the repo and the block editor does not seem to work. It does not allow me to edit anything...
Also, in the ReadMe you mention it has JIT support... Does this mean I can add my custom colors eg: `text-[#5DADE2]`?

Looking forward to your repsonse and assistance

**Comment by jeffreyvr** [comment]
Hi @Blusoup,

Thanks! Have you cloned this repo or the original one? https://github.com/jeffreyvr/tailpress

I know there was an issue a while back with the block editor not working correctly, but that was fixed.

You should be able to use the custom colors as you mentioned, but this works if you use https://github.com/jeffreyvr/tailpress as a starting point. When this example repo was created, JIT was not available yet.
